version: '2'
services:
    db: 
        image: mysql
        environment:
            MYSQL_ROOT_PASSWORD: root 
            MYSQL_USER: root
            MYSQL_DATABASE: "assur_link"
        volumes:
            - mysql_data_assur:/var/lib/mysql
            - ./back_api/fixtures/:/docker-entrypoint-initdb.d:ro

    php:
        build: ./docker/php-fpm
        expose:
            - 9000
        volumes:
            - ./back_api/:/var/www/symfony
            - ./docker/logs/symfony/:/var/www/symfony/var/logs/
        links:
            - db

    nginx:
        image: nginx
        ports:
            - 80:80
        links:
            - php
        volumes_from:
            - php
        volumes:
            - ./docker/logs/nginx/:/var/log/nginx/
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

    db_admin:
          image: adminer
          links:
              - db
          ports:
              - 8081:8080
volumes:
  mysql_data_assur: {}
 

